version: '3'

volumes:
  postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: portal_web
    depends_on:
      - db
    volumes:
      - .:/app
    command: /start

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: portal_postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: always
    image: protal_nginx
    depends_on:
      - web
    volumes:
      - ./etc/ssl:/etc/nginx/ssl
    ports:
      - '80:80'
      - '443:443'
    environment:
      - TZ=UTC
      - LETSENCRYPT=true
